INSERT INTO ACCOUNT_FRIENDS (ACCOUNT_ID, FRIENDS_ID)
VALUES (1,2);


DROP TABLE ACCOUNT_FRIENDS
DROP TABLE ACCOUNT_FRIEND_REQUESTS


INSERT INTO  FRIEND_REQUEST  (ID,DATE, REQUESTER_ID, TO_ID)
VALUES (1,'1999-12-12', 1,3);

INSERT INTO ACCOUNT_FRIEND_REQUESTS (ACCOUNT_ID, FRIEND_REQUESTS_ID)
VALUES (1,1)